apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gateway-bff
  name: gateway-bff
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  selector:
    app: gateway-bff
  ports:
    - port: 8080
