spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-22151406.okta.com/oauth2/default

kotlin-service:
  url: http://kotlin-service.dev.svc.cluster.local:8080
